In [1]:
int(1563344702709)

1563344702709

In [4]:
from datetime import datetime
timestamp = 1563344702
dt_object = datetime.fromtimestamp(timestamp)

In [5]:
dt_object

datetime.datetime(2019, 7, 17, 14, 25, 2)

In [7]:
dt_object.replace(microsecond=709000)

datetime.datetime(2019, 7, 17, 14, 25, 2, 709000)

In [12]:
datetime.now()

datetime.datetime(2019, 7, 29, 17, 9, 30, 386164)

In [13]:
a = 1
aa = [1,2]
a in aa

True

In [59]:
import json    # or `import simplejson as json` if on Python < 2.6

json_string = u'{ "@id":"123456789"}'
obj = json.loads(json_string) 
obj["@id"]

'123456789'

In [15]:
aa = {1: 12}

In [17]:
aa[1]

12

In [18]:
from enum import IntEnum
class Shape(IntEnum):
     circle = 1
     square = 2

In [21]:
Shape.circle == 1

True

In [23]:
class Event(IntEnum):
    '''
    Please make sure that the value is ascendant according to its sequence
    '''
    rest_request_filtering_start = 1
    rest_request_filtering_end = 2
    rest_request_body_reading_start = 3
    rest_request_body_reading_end = 4

    webapi_get_json_results_start = 5

    iserver_compress_result_start = 10
    iserver_compress_result_end = 11

    webapi_xml_cmd_receive_response = 19
    webapi_get_json_results_return = 20

    rest_response_filtering_start = 21
    rest_response_filtering_end = 22
    rest_response_body_writing_start = 23
    rest_response_body_writing_end = 24

    
MESSAGE_TO_EVENT = {
    "Request filtering - start": Event.rest_request_filtering_start,
    "Request filtering - end": Event.rest_request_filtering_end,
    "Request body reading - start": Event.rest_request_body_reading_start,
    "Request body reading - end": Event.rest_request_body_reading_end,
    "Response filtering - start": Event.rest_response_filtering_start,
    "Response filtering - end": Event.rest_response_filtering_end,
    "Response body writing - start": Event.rest_response_body_writing_start,
    "Response body writing - end": Event.rest_response_body_writing_end
}

In [29]:
MESSAGE_TO_EVENT.get("message, None")

In [35]:
"a,b ".split("|")[0].strip().startswith('a')

True

In [40]:
len(aa)

1

In [43]:
set(aa.keys())

{1}

In [42]:
assert 1 != 1

AssertionError: 

In [46]:
None or "b"

'b'

In [47]:
aaa = [e.name for e in Event]
print(aaa)

['rest_request_filtering_start', 'rest_request_filtering_end', 'rest_request_body_reading_start', 'rest_request_body_reading_end', 'webapi_get_json_results_start', 'iserver_compress_result_start', 'iserver_compress_result_end', 'webapi_xml_cmd_receive_response', 'webapi_get_json_results_return', 'rest_response_filtering_start', 'rest_response_filtering_end', 'rest_response_body_writing_start', 'rest_response_body_writing_end']


In [49]:
b = "1232"
b.find("2")

1

In [50]:
from dateutil.parser import parse

In [53]:
a = parse("2019-07-17 03:26:46.120-04:00")

In [57]:
a

datetime.datetime(2019, 7, 17, 3, 26, 46, 120000, tzinfo=tzoffset(None, -14400))

In [54]:
a.timestamp()

1563348406.12

In [55]:
b = parse("2019-07-29T17:31:30.002+08:00")

In [56]:
b

datetime.datetime(2019, 7, 29, 17, 31, 30, 2000, tzinfo=tzoffset(None, 28800))

In [58]:
b.timestamp()

1564392690.002

In [64]:
xml_str = '<st><sst><st><cmd><gjs sid="024DF2B65843CA99E7FA6F4E570B6939" mid="E487A59C4B8D581DCE672993F708AE39" resf="33554433" fg="0" stid="-1"><extendable_parameter/></gjs></cmd></st></sst></st>'
import xml.etree.ElementTree as ET
ET.fromstring(xml_str).find("sst").find("st").find("cmd").find("gjs")

<Element 'gjs' at 0x10d5379f8>

In [65]:
a = 1
b = {a:2}
b

{1: 2}

In [9]:
import torch

x = torch.randn(2, 2)
print(x)
print(x.view(-1))

tensor([[ 0.1178, -1.0797],
        [ 0.9359, -0.5268]])
tensor([ 0.1178, -1.0797,  0.9359, -0.5268])


In [1]:
x = None
x += "s"

TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

In [4]:
abbb = "abc"
abbb.find("d")

-1

In [2]:
a = [2,3,4,1]
a.sort()

In [3]:
a

[1, 2, 3, 4]

In [4]:
a

[1, 2, 3, 4]

In [5]:
import torch

In [6]:
torch.tensor(a)

tensor([1, 2, 3, 4])

In [1]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.


In [8]:
import numpy as np
torch.from_numpy(np.array([1,2]))

tensor([1, 2])

In [5]:
%debug
import ipdb

# Must be in a function, or the program would report error
def test():
    var1 = 23
    ipdb.set_trace()
    var2 = "a"
    var3 = var2 + "b"

test()

> /Users/ryu/miniconda2/envs/a2/lib/python3.7/site-packages/IPython/core/compilerop.py(100)ast_parse()
     98         Arguments are exactly the same as ast.parse (in the standard library),
     99         and are passed to the built-in compile function."""
--> 100         return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)
    101 
    102     def reset_compiler_flags(self):

ipdb> c
> <ipython-input-5-d62c493cda0b>(7)test()
      6     ipdb.set_trace()
----> 7     var2 = "a"
      8     var3 = var2 + "b"

ipdb> n
> <ipython-input-5-d62c493cda0b>(8)test()
      7     var2 = "a"
----> 8     var3 = var2 + "b"
      9 

ipdb> n
--Return--
None
> <ipython-input-5-d62c493cda0b>(8)test()
      7     var2 = "a"
----> 8     var3 = var2 + "b"
      9 

ipdb> n
--Call--
> /Users/ryu/miniconda2/envs/a2/lib/python3.7/site-packages/IPython/core/displayhook.py(247)__call__()
    246 
--> 247     def __call__(self, result=None):
    248         """Printing with history cache mana

In [3]:
ip = get_ipython()
ip.showtraceback??

In [1]:
import pixiedust

Pixiedust database opened successfully


In [7]:
%%pixie_debugger

var1 = 23
var2 = "a"
var3 = var2 + "b"

In [1]:
max([1,2,3])

3

In [3]:
[1,2,3] + [1]

[1, 2, 3, 1]

In [10]:
import torch.nn as nn
import numpy

In [7]:
tensor = torch.tensor([[[1,2]],[[5,6]]])

In [8]:
tensor.size()

torch.Size([2, 1, 2])

In [9]:
tensor.permute(1,0,2)

tensor([[[1, 2],
         [5, 6]]])

In [19]:
m = nn.Conv1d(16, 33, 3, stride=2)
input = torch.randn(2, 20, 16, 50)
output = m(input)

RuntimeError: Expected 3-dimensional input for 3-dimensional weight [33, 16, 3], but got 4-dimensional input of size [2, 20, 16, 50] instead

In [24]:
a, b, c, d = input.size()

In [25]:
a

2

In [20]:
input.view(-1, 16,50)

tensor([[[ 2.7938e-01, -1.3240e+00,  1.0611e+00,  ..., -1.1579e+00,
          -6.0656e-01,  2.1734e+00],
         [-1.0679e+00,  1.4412e-01, -1.3564e+00,  ...,  1.5838e+00,
           2.0178e+00, -4.5850e-01],
         [-9.4195e-01, -1.8194e-01, -6.0372e-01,  ...,  5.8038e-01,
          -1.9109e-03, -1.7684e+00],
         ...,
         [-1.8971e+00,  1.6883e+00, -8.4108e-01,  ..., -2.1428e-01,
          -8.0993e-01,  1.4136e-01],
         [ 1.6860e+00, -6.5614e-02,  8.8418e-01,  ..., -2.3878e+00,
           9.5704e-01,  4.1788e-01],
         [ 2.8824e-01,  1.6714e-01, -1.3251e-01,  ..., -7.8961e-01,
          -7.1012e-02, -1.3423e+00]],

        [[ 6.1621e-01,  3.9183e-01, -9.5604e-01,  ..., -4.2154e-01,
          -3.1290e-02,  5.8889e-02],
         [ 2.3294e-01, -5.5072e-01,  1.3379e+00,  ..., -5.4659e-01,
           1.2099e+00,  6.5223e-01],
         [-4.7523e-01, -8.5225e-01,  3.6582e-01,  ..., -5.5553e-01,
          -1.5770e+00,  4.7498e-01],
         ...,
         [-1.4308e+00, -5

In [31]:
m = nn.MaxPool1d(50)
input = torch.randn(20, 16, 50)
output = m(input).squeeze(-1)

In [32]:
output.size()

torch.Size([20, 16])

In [30]:
?nn.MaxPool1d